config/routes.rb
Rails.application.routes.draw do
  root "projects#index"

  get 'login' => 'user_sessions#new', :as => :login
  get 'logout' => 'user_sessions#destroy', :as => :logout

  resources :projects, only: [:index, :new, :create, :show] do
    resources :pledges, only: [:create]
    resources :rewards, only: [:new, :create, :destroy]
    resources :comments
  end
  resources :users, only: [:new, :create, :destroy]
  resources :user_sessions, only: [:new, :create, :logout]

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :project
end

app/models/pledge.rb
class Pledge < ApplicationRecord
  belongs_to :user
  belongs_to :project

  validates :dollar_amount, presence: true
  validates :user, presence: true
  validate :owner_back_own_project

  def owner_back_own_project
    if user == project.owner
      errors.add :user, "Cannot back own project"
    end
  end
  
end

app/models/project.rb
class Project < ActiveRecord::Base
  has_many :rewards
  has_many :pledges
  has_many :backers, through: :pledges, source: :user
  has_many :comments
  belongs_to :owner, class_name: 'User'

  # validates :title, :description, :goal, :start_date, :end_date, presence: true

  validate :start_in_future
  validate :end_date_is_later_than_start_date
  validate :goal_must_be_positive



  def start_in_future
    if self.start_date < Date.today
      errors.add(:base, "Start date must be in furture")
    end
  end

  def end_date_is_later_than_start_date
    if self.start_date >= self.end_date
      errors.add(:base, "End date must be later than start date")
    end
  end

  def goal_must_be_positive
    if self.goal.to_i < 0
      errors.add(:base, "Goal must be positive")
    end
  end





end

app/models/reward.rb
class Reward < ActiveRecord::Base
  belongs_to :project

 validates :description, :dollar_amount, presence: true

 validate :limit_for_reward
 validate :dollar_amount_must_be_positive

 def limit_for_reward
   count = Project.find(self.project_id).rewards.count
   if count >= 5
     errors.add :reward, "Alreday 5 rewards"
   end
 end

 def dollar_amount_must_be_positive
   if self.dollar_amount <= 0
     errors.add :dollar_amount, "dollar amount must be positive"
   end
 end

  def max_quantity_for_reward

  end
end

app/models/user.rb
class User < ActiveRecord::Base
  authenticates_with_sorcery!
  # has_secure_password
  has_many :pledges

  validates :password, length: { minimum: 8, too_short: "password characters is too short"}, on: :create
  validates :password, confirmation: true, on: :create
  validates :password_confirmation, presence: true, on: :create

  validates :email, uniqueness: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  # helper_method :current_user
  # def current_user
  #   user_sessions[:user_id] && User.find(user_sessions[:user_id])
  # end
  private
  def not_authenticated
    redirect_to login_path, alert: "Please login first"
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

  def create
    @project = Project.find(params[:project_id])
    @comment = @project.comments.new
    @comment.comment = params[:comment][:comment]

    if @comment.save
      redirect_to @project

    else
      render 'projects/show'
    end
  end

end

app/controllers/pledges_controller.rb
class PledgesController < ApplicationController
  before_action :require_login

  def create
    @project = Project.find(params[:project_id])

    @pledge = @project.pledges.build(pledge_params)
    @pledge.user = current_user

    if @pledge.save
      redirect_to project_url(@project), notice: "You have successfully backed #{@project.title}!"
    else
      flash.now[:alert] = @pledge.errors.full_messages.first
      render 'projects/show'
    end
  end

  private

  def pledge_params
    params.require(:pledge).permit(:dollar_amount)
  end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_action :require_login, only: [:new, :create]

  def index
    @projects = Project.all
    @projects = @projects.order(:end_date)
  end

  def show
    @project = Project.find(params[:id])
    @comment = @project.comments.new
  end

  def new
    @project = Project.new
    @project.rewards.build
  end

  def create
    @project = Project.new(project_params)
    @project[:owner_id] = current_user.id
    if @project.save
      redirect_to projects_url
    else
      render :new
    end
   end

  private
  def project_params
    params.require(:project).permit(:title, :description, :goal, :start_date, :end_date, :image)
  end
end

app/controllers/rewards_controller.rb
class RewardsController < ApplicationController
  before_action :load_project

  def new
    @reward = Reward.new
  end

  def create
    @reward = @project.rewards.build(reward_params)

    if @reward.save
      redirect_to project_url(@project), notice: 'Reward created'
    else
      render :new
    end
  end

  def destroy
    @reward = Reward.find(params[:id])
    @reward.destroy

    redirect_to project_url(@project), notice: 'Reward successfully removed'
  end

  private

  def load_project
    @project = Project.find(params[:project_id])
  end

  def reward_params
    params.require(:reward).permit(:dollar_amount, :description)
  end
end

app/controllers/user_sessions_controller.rb
class UserSessionsController < ApplicationController
  def new
    @user = User.new
  end

  def create
     if @user = login(params[:email], params[:password], params[:remember_me])
      redirect_back_or_to(root_url, notice: 'Login successful')
    else
      flash.now[:alert] = 'Login failed'
      render action: 'new'
    end
  end
  # def destroy
  #   user_session[:user_id] = nil
  #
  #   flash[:notice] = "You're logged out!"
  #   redirect_to root_url
  # end
  def destroy
    logout
    redirect_to root_url, notice: 'Logged out!'
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      auto_login(@user)
      redirect_to projects_url
    else
      render 'new'
    end
  end

  private
  def user_params
    params.require(:user).permit(:first_name, :last_name, :email, :password, :password_confirmation)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/pledges_helper.rb
module PledgesHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/helpers/rewards_helper.rb
module RewardsHelper
end

app/helpers/user_sessions_helper.rb
module UserSessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Crowdfunder</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <%= stylesheet_link_tag    "https://fonts.googleapis.com/css?family=Josefin+Sans:700|Libre+Baskerville" %>
    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
    <%= csrf_meta_tags %>
  </head>

  <body>
    <header class="site-header">
      <h1 class="logo">Crowdfunder</h1>

      <nav class="site-nav">
        <% if current_user %>
          <%= link_to "Logout", logout_path %>  |  
          <%= link_to "Home", projects_path %>
        <% else %>
          <%= link_to "Register", new_user_path %> |
          <%= link_to "Login", :login %>
        <% end %>
      </nav>
    </header>
    <% if flash.any? %>
      <% flash.each do |key, message| %>
        <div class="<%= key %>"><%= message %></div>
      <% end %>
    <% end %>

    <main>
      <%= yield %>
    </main>
  </body>
</html>

app/views/projects/_form.html.erb
<% if @project.errors.any? %>
  <ul>
    <% @project.errors.full_messages.each do |m| %>
      <li><%= m %></li>
    <% end %>
  </ul>
<% end %>

<%= form_for(@project, html: {multipart: true}) do |f| %>
  <div>
    <%= f.label :title %>
    <%= f.text_field :title %>
  </div>

  <div>
    <%= f.label :description %>
    <%= f.text_field :description %>
  </div>

  <div>
    <%= f.label :goal %>
    <%= f.number_field :goal %>
  </div>

  <div>
    <%= f.label :image %>
    <%= f.text_field :image %>
  </div>

  <div>
    <%= f.label :start_date %>
    <%= f.datetime_select :start_date %>
  </div><br>

  <div>
    <%= f.label :end_date %>
    <%= f.datetime_select :end_date %>
  </div>

  <%= f.submit "Submit" %>
<% end %>

app/views/projects/index.html.erb
<%= link_to "New Project", new_project_path %>

<% @projects.each do |project| %>
  <article class="project">
    <%= link_to project, class: 'project-link' do %>
      <figure class="project-image">
        <% if project.image %>
          <%= image_tag project.image %>
        <% else %>
          <%= image_tag ActionController::Base.helpers.asset_path("default.jpg") %>
        <% end %>
      </figure>
      <h1 class="project-title"><%= project.title %></h1>
      <time class="project-days-left">
        <%= icon('clock-o') %>
        <%= "#{time_ago_in_words(project.end_date)} #{( project.end_date > Time.now.utc ) ? 'remaining' : 'past deadline'}" %></time>
    <% end %>
  </article>
<% end %>

app/views/projects/new.html.erb
<h1>Create a new project</h1>

<%= render 'form' %>

app/views/projects/show.html.erb
<h1><%= @project.title %></h1>

<% if @project.image.present? %>
  <%= image_tag @project.image %>
<% end %>

<p><%= @project.description %></p>
<p>Goal: <%= number_to_currency(@project.goal) %></p>

<p>Fundraising starts: <%= @project.start_date.strftime("%A %b %d %Y") %></p>
<p>Deadline: <%= @project.end_date.strftime("%A %b %d %Y") %></p>
<time class="project-days-left-show">
  <%= icon('clock-o') %>
  <%= "#{time_ago_in_words(@project.end_date)} #{( @project.end_date > Time.now.utc ) ? 'remaining' : 'past deadline'}" %></time>

<%= form_for [@project, Pledge.new] do |f| %>
  <%= f.number_field :dollar_amount, value: @project.rewards.minimum(:dollar_amount), step: 0.01 %>
  <%= f.submit "Pledge" %>
<% end %>

<h2>Rewards</h2>
<% @project.rewards.each do |reward| %>
  <p><%= number_to_currency(reward.dollar_amount) %></p>
  <p><%= reward.description %></p>

  <p>
    <small>
      <%= link_to "Remove reward", project_reward_path(@project, reward), method: 'delete' %>
    </small>
  </p>
<% end %>

<%= link_to "Add new reward", new_project_reward_path(@project) %>


<h2>Pledge</h2>
<% sum = 0 %>
<% num_of_pledges = 0 %>
<% @project.pledges.each do |p| %>
  <p><%= User.find(p.user_id).first_name %> makes <%= p.dollar_amount %>$ pledge</p>
  <% sum += p.dollar_amount %>
  <% if User.find(p.user_id).id == current_user&.id %>
    <% num_of_pledges += 1 %>
  <% end %>
<% end %>
<h2>Total amount pledged: $<%= sum %></h2>
<h2>You have backed this project <%= num_of_pledges %> times.</h2>

<h2>Rewards Claimed</h2>
<% @project.rewards.each do |p| %>
  <p><%= User.find(p.project_id).first_name %> claimed a reward of <%= p.description %> reward</p>
<% end %>


<h3>Comments</h3>

<%= form_for [@project, @comment] do |f| %>
<%= f.label :comment %>
<%= f.text_area :comment %>
<%= f.submit %>
<% end %>

<hr>

<% @project.comments.each do |comment| %>
<%= comment.comment %>
<hr>
<% end %>

app/views/rewards/new.html.erb
<h1>Add a reward for <%= @project.title %></h1>

<%= form_for [@project, @reward] do |f| %>
  <div>
    <%= f.label :dollar_amount %>
    <%= f.number_field :dollar_amount, step: 0.01 %>
  </div>

  <div>
    <%= f.label :description %>
    <%= f.text_area :description %>
  </div>

  <%= f.submit %>
<% end %>

app/views/user_sessions/_form.html.erb
<%= form_tag user_sessions_path, :method => :post do %>
  <div class="field">
    <%= label_tag :email %><br />
    <%= text_field_tag :email %>
  </div>
  <div class="field">
    <%= label_tag :password %><br />
    <%= password_field_tag :password %>
  </div>

  <div class="field">
    <%= check_box_tag :remember_me %><br />
    <%= label_tag :remember_me %>
  </div>

  <div class="actions">
    <%= submit_tag "Login" %>
  </div>
<% end %>

app/views/user_sessions/new.html.erb
<h1>Login</h1>

<%= render 'form' %>

<%= link_to 'Back', root_path %>

app/views/users/_form.html.erb
<%= form_for @user do |f| %>
  <div class="field">
     <%= f.label :first_name %><br />
     <%= f.text_field :first_name %>
  </div>

  <div class="field">
     <%= f.label :last_name %><br />
     <%= f.text_field :last_name %>
  </div>

  <div class="field">
     <%= f.label :email %><br />
     <%= f.text_field :email %>
  </div>

  <div class="field">
     <%= f.label :password %><br />
     <%= f.password_field :password %>
  </div>
  <div class="field">
     <%= f.label :password_confirmation %><br />
     <%= f.password_field :password_confirmation %>
  </div>

  <div class="field">
     <%= f.submit %>
  </div>

<% end %>

app/views/users/new.html.erb
<h1>Sign up?</h1>

<%= render 'form' %>

<%= link_to 'Back', root_path %>